### ISSUE TITLE
HpCF averages

### ISSUE THREAD

**Issue by DeLub** [ShanonPearce/ASH-BRIRs#5]
Hi,

I'm trying out your files. Very interesting! :)

Question, though, regarding the HpCFs: for the Sennheiser HD600 (and for other types as well) you provide 3 different averages. What's the difference between those, and which should I use?

Thanks.

Regards,
Alex

**Comment by ShanonPearce** [comment]
If multiple averages are provided, it is due to significant variations in measured responses. Similar responses were grouped together and an average was created for each group. If these measured variations are due to different tunings of the same headphone, then there should be an average for each 'tuning'. An average over all HpCFs for the headphone is also provided as it is not known where exactly these variations come from - it could simply be from measurement variations for example. I recommend testing out each one to discover which is the best match for your headphones.

In the case of Sennheiser HD600: 
Avg_1 is an average of the HpCFs with a peak at approx. 7kHz.
Avg_2 is an average of the HpCFs with reduced gain at high freqs.
Avg_3 the average across all of the HpCFs.

It's also worth checking out the HD650 HpCFs and the Massdrop_HD6xx as they measure quite similar.

**Comment by DeLub** [comment]
Thanks for the explanation. I'll test with all 3.
